import 'package:flutter/material.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'appName': 'News Today',
      'appSubtitle': 'Your daily dose of what matters.',
      'searchNews': 'Search news...',
      'all': 'All',
      'sports': 'Sports',
      'gold': 'Gold',
      'politics': 'Politics',
      'economy': 'Economy',
      'technology': 'Technology',
      'topStories': 'Top Stories',
      'latestStories': 'Latest Stories',
      'searchResults': 'Search Results',
      'resultsFor': 'Results for',
      'stories': 'stories',
      'featured': 'Featured',
      'latestNews': 'LATEST NEWS',
      'readArticle': 'Read Article',
      'readFullArticle': 'Read Full Article',
      'share': 'Share',
      'save': 'Save',
      'saved': 'Saved',
      'savedNews': 'Saved News',
      'noSavedNews': 'No saved news',
      'noSavedNewsDescription': 'News you save will appear here.',
      'loadingLatestStories': 'Loading latest stories...',
      'unableToLoadNews': 'Unable to load news',
      'checkConnection': 'Check your connection and try again.',
      'tryAgain': 'Try Again',
      'noResultsFound': 'No results found',
      'tryAnotherKeyword': 'Try searching with another keyword.',
      'noNewsAvailable': 'No news available',
      'noStoriesRightNow': 'There are no stories to show right now.',
      'recently': 'Recently',
      'unknownAuthor': 'Unknown author',
      'language': 'Language',
      'english': 'English',
      'arabic': 'العربية',
      'removeFromSaved': 'Remove from saved',
      'addedToSaved': 'Added to saved',
      'removedFromSaved': 'Removed from saved',
      'darkMode': 'Dark Mode',
      'lightMode': 'Light Mode',
    },
    'ar': {
      'appName': 'أخبار اليوم',
      'appSubtitle': 'كل ما يهمك من الأخبار يوميًا.',
      'searchNews': 'ابحث عن الأخبار...',
      'all': 'الكل',
      'sports': 'رياضة',
      'gold': 'ذهب',
      'politics': 'سياسة',
      'economy': 'اقتصاد',
      'technology': 'تكنولوجيا',
      'topStories': 'أهم الأخبار',
      'latestStories': 'أحدث الأخبار',
      'searchResults': 'نتائج البحث',
      'resultsFor': 'نتائج البحث عن',
      'stories': 'خبر',
      'featured': 'مميز',
      'latestNews': 'أحدث الأخبار',
      'readArticle': 'قراءة الخبر',
      'readFullArticle': 'قراءة الخبر كاملًا',
      'share': 'مشاركة',
      'save': 'حفظ',
      'saved': 'محفوظ',
      'savedNews': 'الأخبار المحفوظة',
      'noSavedNews': 'لا توجد أخبار محفوظة',
      'noSavedNewsDescription': 'الأخبار التي تقوم بحفظها ستظهر هنا.',
      'loadingLatestStories': 'جاري تحميل أحدث الأخبار...',
      'unableToLoadNews': 'تعذر تحميل الأخبار',
      'checkConnection': 'تحقق من اتصالك بالإنترنت وحاول مرة أخرى.',
      'tryAgain': 'حاول مرة أخرى',
      'noResultsFound': 'لم يتم العثور على نتائج',
      'tryAnotherKeyword': 'حاول البحث باستخدام كلمة أخرى.',
      'noNewsAvailable': 'لا توجد أخبار',
      'noStoriesRightNow': 'لا توجد أخبار متاحة للعرض حاليًا.',
      'recently': 'مؤخرًا',
      'unknownAuthor': 'كاتب غير معروف',
      'language': 'اللغة',
      'english': 'English',
      'arabic': 'العربية',
      'removeFromSaved': 'إزالة من المحفوظات',
      'addedToSaved': 'تم حفظ الخبر',
      'removedFromSaved': 'تمت إزالة الخبر من المحفوظات',
      'darkMode': 'الوضع الداكن',
      'lightMode': 'الوضع الفاتح',
    },
  };

  static String text(
      BuildContext context,
      String key,
      ) {
    final languageCode = Localizations.localeOf(context).languageCode;

    return _strings[languageCode]?[key] ??
        _strings['en']?[key] ??
        key;
  }
}